[package]
name = "lumina_guardian"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.22", features = ["glow"] }
egui = "0.22"
image = { version = "0.24", features = ["png", "jpeg"] }
rand = "0.8"
wasm-bindgen-futures = "0.4"

# THIS IS THE FIX: This tells the randomizer to use the browser's JavaScript engine
getrandom = { version = "0.2", features = ["js"] }
log = "0.4.29"
